DATABASE_NAME: panda-db
DATABASE_USER: panda
DATABASE_PASSWORD: panda
DATABASE_HOST: localhost
DATABASE_PORT: 5723

SQLALCHEMY_DATABASE_URI: postgresql://panda:panda@localhost:5723/panda-db
SECRET_KEY: ENTER YOUR SECRET KEY
SQLALCHEMY_TRACK_MODIFICATIONS: False